version: "3"

services:
  weather_app1:
    build: 
      context: .
      dockerfile: dockerfile
    image: compose_app 
    container_name: weather_app1
    restart: "on-failure"
    ports:
      - 80:5000
    environment:
      - BG_COLOR=#FF5C5C
    volumes:
      - type: bind 
        source: ./history.json
        target: /weather_app/history.json

