apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: aws-efs-test01
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi