apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.weather_path }}
            pathType: {{ .Values.ingress.type }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.targetPort }}

