# Deployment
deployment:
  name: app-deploy
  namespace: default
  # RS
  replicas: 4
  match_labels: nodejs-app
  pod_label: nodejs-app
  # Deploy strategy
  strategy_type: RollingUpdate
  max_surge: 1
  max_unavailable: 1
  # Container
  container_image: joska99/weather-app:eks
  container_port: 5000
  request_cpu: 200m
  limit_memory: "128Mi"
  limit_cpu: "500m"
  # Deployment configs
  pull_policy: Always
  # deployment_secret: ecr

# Service
service:
  name: app-service
  type: ClusterIP
  selector: nodejs-app
  port: 5000
  # targetPort: 5000
  # nodePort: 32000

cm:
  name: cm
  BG_COLOR: blue

cm2:
  name: cm-green
  BG_COLOR: green